name: CI
on: [pull_request]

env:
  cache-version: v1
  node-version: "12"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kenchan0130/actions-system-info@v1.0.0
        id: system-info
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node-version }}"
      - name: Get npm cache directory path
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3.0.4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ env.cache-version }}-${{ runner.os }}-${{ steps.system-info.outputs.release }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-${{ steps.system-info.outputs.release }}-npm-
      - name: Install Node.js dependences
        run: |
          npm ci
      - name: Run lint
        run: |
          npm run lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node-version }}"
      - name: Get npm cache directory path
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3.0.4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ env.cache-version }}-${{ runner.os }}-${{ steps.system-info.outputs.release }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-${{ steps.system-info.outputs.release }}-npm-
      - name: Install Node.js dependences
        run: |
          npm ci
      - name: Run test
        run: |
          npm run test
      - name: Run package
        run: |
          npm run package
      - name: Run action
        uses: ./
