name: Package
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  cache-version: v1
  node-version: "12"

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kenchan0130/actions-system-info@v1.0.0
        id: system-info
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node-version }}"
      - name: Get npm cache directory path
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ env.cache-version }}-${{ runner.os }}-${{ steps.system-info.outputs.release }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-${{ steps.system-info.outputs.release }}-npm-
      - name: Install Node.js dependences
        run: |
          npm ci
      - name: Run package
        run: |
          npm run package
      - name: Push package
        run: |
          git config --local user.email "1155067+kenchan0130@users.noreply.github.com"
          git config --local user.name "kenchan0130"
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git add -N .
          if git diff --exit-code --quiet;then
            echo "No change."
          else
            git add .
            git commit -m "[skip ci] Create package by ${GITHUB_SHA}"
            git push origin master
          fi
